[phases.setup]
nixPkgs = ["nodejs_22", "git"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["prisma generate", "npm run build"]

[phases.deploy]
cmds = ["npx prisma db push --skip-generate || true"]

[start]
cmd = "npm run start"
