[phases.setup]
nixPkgs = ["nodejs_22", "git"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
  "echo 'DATABASE_URL=\"file:./dev.db\"' > .env",
  "date +%s > /tmp/BUILD_ID && echo \"build: $(cat /tmp/BUILD_ID)\"",
  "prisma generate",
  "npm run build",
]

# Healthcheck to confirm the web server is alive
[healthcheck]
uri = "/api/health"

[start]
cmd = "bash start.sh"
